{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "muffin-currency.serviceAccountName" . }}
  labels:
    {{- include "muffin-currency.labels" . | nindent 4 }}
{{- end }}
