# Source: https://raw.githubusercontent.com/istio/istio/release-1.28/samples/addons/jaeger.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.54
          ports:
            - containerPort: 16686
            - containerPort: 14268
            - containerPort: 14250
            - containerPort: 9411
            - containerPort: 4317
          env:
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: ":9411"
---
kind: Service
apiVersion: v1
metadata:
  name: tracing
  namespace: istio-system
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
    - name: http-query
      port: 80
      protocol: TCP
      targetPort: 16686
    # Note: Change port name if you add '--query.grpc.tls.enabled=true'
    - name: grpc-query
      port: 16685
      protocol: TCP
      targetPort: 16685
    - name: http-collector
      port: 14268
      protocol: TCP
      targetPort: 14268
    - name: grpc-collector
      port: 14250
      protocol: TCP
      targetPort: 14250
    - port: 9411
      targetPort: 9411
      name: http-zipkin
    - port: 4317
      name: grpc-otel
  selector:
    app: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: istio-system
spec:
  type: ClusterIP
  ports:
    - name: jaeger-collector-http
      port: 14268
      targetPort: 14268
      protocol: TCP
    - name: jaeger-collector-grpc
      port: 14250
      targetPort: 14250
      protocol: TCP
    - port: 9411
      targetPort: 9411
      name: http-zipkin
    - port: 4317
      name: grpc-otel
  selector:
    app: jaeger
