apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: muffin-currency-traffic
spec:
  hosts:
    - {{ .Values.currency.serviceName | quote }}
    - {{ printf "%s.%s.svc.cluster.local" .Values.currency.serviceName .Release.Namespace | quote }}
  http:
    - match:
        - uri:
            prefix: {{ .Values.currency.pathPrefix | quote }}
      route:
        - destination:
            host: {{ printf "%s.%s.svc.cluster.local" .Values.currency.serviceName .Release.Namespace | quote }}
            port:
              number: {{ .Values.currency.servicePort }}
      timeout: {{ .Values.currency.timeout | quote }}
      retries:
        attempts: {{ .Values.currency.retries.attempts }}
        perTryTimeout: {{ .Values.currency.retries.perTryTimeout | quote }}
        retryOn: {{ .Values.currency.retries.retryOn | quote }}