apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: muffin-currency-traffic
spec:
  # Wallet calls currency by service name; include both short and FQDN hosts
  hosts:
    - {{ .Values.currency.serviceName | quote }}
    - {{ .Values.currency.serviceHost | quote }}
  http:
    - match:
        - uri:
            prefix: {{ .Values.currency.pathPrefix | quote }}
      route:
        - destination:
            host: {{ .Values.currency.serviceHost | quote }}
            port:
              number: {{ .Values.currency.servicePort }}
      timeout: {{ .Values.currency.timeout | quote }}
      retries:
        attempts: {{ .Values.currency.retries.attempts }}
        perTryTimeout: {{ .Values.currency.retries.perTryTimeout | quote }}
        retryOn: {{ .Values.currency.retries.retryOn | quote }}
