apiVersion: v1
kind: Secret
metadata:
  name: external-postgres-auth
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    app: external-postgres
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
