{{- if .Values.migrations.enabled }}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "muffin-wallet.fullname" . }}-migrate-{{ now | unixEpoch }}
  labels:
    {{- include "muffin-wallet.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "muffin-wallet.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: liquibase-migrate
          image: "{{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag }}"
          imagePullPolicy: {{ .Values.migrations.image.pullPolicy }}
          env:
            - name: LIQUIBASE_COMMAND_URL
              value: "{{ .Values.migrations.db.url }}"
            - name: LIQUIBASE_COMMAND_USERNAME
              value: "{{ .Values.migrations.db.username }}"
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.migrations.db.passwordSecretName }}
                  key: {{ .Values.migrations.db.passwordSecretKey }}
          command:
            - "sh"
            - "-c"
            - >
              lpm add postgresql --global &&
              liquibase
              --searchPath=/liquibase/changelog
              --changeLogFile=changelog-master.sql
              update
          volumeMounts:
            - name: liquibase-changelog
              mountPath: /liquibase/changelog
      volumes:
        - name: liquibase-changelog
          configMap:
            name: {{ include "muffin-wallet.fullname" . }}-liquibase-changelog

---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "muffin-wallet.fullname" . }}-rollback-{{ now | unixEpoch }}
  labels:
    {{- include "muffin-wallet.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "muffin-wallet.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: liquibase-rollback
          image: "{{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag }}"
          imagePullPolicy: {{ .Values.migrations.image.pullPolicy }}
          env:
            - name: LIQUIBASE_COMMAND_URL
              value: "{{ .Values.migrations.db.url }}"
            - name: LIQUIBASE_COMMAND_USERNAME
              value: "{{ .Values.migrations.db.username }}"
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.migrations.db.passwordSecretName }}
                  key: {{ .Values.migrations.db.passwordSecretKey }}
          command:
            - "sh"
            - "-c"
            - >
              lpm add postgresql --global &&
              liquibase
              --searchPath=/liquibase/changelog
              --changeLogFile=changelog-master.sql
              rollbackCount 1
          volumeMounts:
            - name: liquibase-changelog
              mountPath: /liquibase/changelog
      volumes:
        - name: liquibase-changelog
          configMap:
            name: {{ include "muffin-wallet.fullname" . }}-liquibase-changelog

{{- end }}