{{- if .Values.migrations.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "muffin-wallet.fullname" . }}-liquibase-changelog
  labels:
    {{- include "muffin-wallet.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-rollback
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  changelog-master.sql: |
    --liquibase formatted sql

    -- changeset demo:1
    CREATE TABLE IF NOT EXISTS demo_migration (
                                                  id          SERIAL PRIMARY KEY,
                                                  description TEXT        NOT NULL,
                                                  created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    -- rollback DROP TABLE IF EXISTS demo_migration;
{{- end }}
