{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "muffin-wallet.fullname" . }}-postgres
  labels:
    app: {{ include "muffin-wallet.name" . }}-postgres
    {{- include "muffin-wallet.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
      protocol: TCP
      name: postgres
  selector:
    app: {{ include "muffin-wallet.name" . }}-postgres
{{- end }}
