{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "muffin-wallet.fullname" . }}-postgres
  labels:
    {{- include "muffin-wallet.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: "{{ .Values.db.name }}"
  POSTGRES_USER: "{{ .Values.db.user }}"
  POSTGRES_PASSWORD: "{{ .Values.db.password }}"
{{- end }}
