apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name | quote }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- toYaml .Values.namespace.labels | nindent 4 }}
